[package]
name = "day_10"
version = "0.1.0"
edition = "2021"
authors = ["Dennis Pettersson <mail@dennispettersson.se>"]

[lib]
doctest = false

[[bin]]
name = "day_10"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
