[package]
name = "day_10"
version = "0.1.0"
authors = ["Dennis Pettersson <mail@dennispettersson.se>"]
edition = "2018"

[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"

[profile.release]
lto = true
panic = "abort"
