[package]
name = "day_03"
version = "0.1.0"
authors = ["Dennis Pettersson <mail@dennispettersson.se>"]
edition = "2018"
autobins = false

[lib]
doctest = false

[[bin]]
name = "day_03"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
