[package]
name = "day_06"
version = "0.1.0"
authors = ["Dennis Pettersson <mail@dennispettersson.se>"]
edition = "2018"
autobins = false

[lib]
doctest = false

[[bin]]
name = "day_06"

[dependencies]
